#define  WM_TRACKPOS  (WM_USER+22)  
#define  WM_TRACKSTOPPED (WM_USER+34)
#define  WM_DRAWSPECTRUM (WM_PAINT+913)
#define  WM_ADDFOLDERED  (WM_USER+35)

//配置需要生效和保存
#define  WM_CONFIGTOSAVE (WM_USER+36)